### ISSUE TITLE
Problem with the creation of Grid_UY25_Tetrapods

### ISSUE THREAD

**Issue by DinoBiancolini** [KaiHsiangHu/iNEXT.4steps#5]
Dear Kai HsiangHu,
thank you for sharing the scripts of your very interesting work!
I'm having issues creating the object "Grid_UY25_Tetrapods", I get this error:
Error in st_geos_binop("contains", x, y, sparse = sparse, prepared = prepared,  : 
  st_crs(x) == st_crs(y) is not TRUE
I didn't change data or scripts in anyway.
Thanks in advance for your help.
Best regards,
Dino

**Comment by DinoBiancolini** [comment]
I've solved it with st_crs(Grid_UY25) <- st_crs(Tetrapods_GIS)

**Comment by KaiHsiangHu** [comment]
OK, thanks for your testing.  Wish our package can help you.

Best regards
